### ISSUE TITLE
linker error maybe ?

### ISSUE THREAD

**Issue by matxeluu** [PhVanMin/Pikachuuu#1]
I download ur code and try run the Main.cpp file using Sublime Text 3 on g++ but it continuously showing these lines:
undefined reference to `initWindow(int, int)'
undefined reference to `mainMenu()'
undefined reference to `getPlayerInfo(player&)'
undefined reference to `normalMode(player&)'
undefined reference to `getPlayerInfo(player&)'
undefined reference to `difficultMode(player&)'
undefined reference to `readLeaderBoard()'

Can u show me the way to run it

**Comment by PhVanMin** [comment]
I think it's linker error. You can go to this link "https://stackoverflow.com/questions/52814491/how-to-compile-multiple-files-in-sublime-text-3" to fix the problem

If you cant fix it, I recommend you try it on visual studio/visual studio code or other IDEs that support linking multiple files
